export CURRENT_JDK=$(JAVA_HOME)
export JC=$(CURRENT_JDK)/bin/javac
export JVM=$(CURRENT_JDK)/bin/java
export JAR=$(CURRENT_JDK)/bin/jar
export JAR_FLAGS=-cf
export libdir=lib/
export PROJ_JARS=$(shell find $(jarsdir) -follow -name \*.jar -printf %p:)
export classpath=$(libdir)/vesetavias.jar:$(CURRENT_JDK)/jre/lib/rt.jar:$(EXT_JARS):$(PROJ_JARS):.
export JIKES_FLAGS= -classpath $(classpath) -d $(classesdir)

# arch-tag: 9f1baec3-0d61-4c10-87f1-c292fab80c7c
